### ISSUE TITLE
gtsrcmap execution failed (Caught St12out_of_range at the top level: vector::_M_range_check)

### ISSUE THREAD

**Issue by hawkingsteven** [gammapy/enrico#117]
Hello, I encountered this error while running my analysis, I have attached my error message and my _PowerLaw2_model.xml file in a pastebin link (https://pastebin.com/Drm30rBF). Can you help me solve this error?

# ************************************************************
# ***   8   gtsrcmap --- Make a source map
# ************************************************************
time -p /home/szakirov/Desktop/SRMP/ScienceTools-v11r5p3-fssc-20180124-x86_64-unknown-linux-gnu-libc2.17/x86_64-unknown-linux-gnu-libc2.17/bin/gtsrcmaps scfile=/home/szakirov/Desktop/SRMP/nu_65274589/spacecraft/lat_spacecraft_merged.fits sctable="SC_DATA" expcube=/home/szakirov/Desktop/SRMP/nu_65274589/_LAT_Analysis_ltCube.fits cmap=/home/szakirov/Desktop/SRMP/nu_65274589/_LAT_Analysis_CCUBE.fits srcmdl=/home/szakirov/Desktop/SRMP/nu_65274589/_PowerLaw2_model.xml bexpmap=/home/szakirov/Desktop/SRMP/nu_65274589/_LAT_Analysis_BinnedMap.fits wmap=none outfile=/home/szakirov/Desktop/SRMP/nu_65274589/_LAT_Analysis_srcMap.fits irfs="CALDB" evtype="INDEF" convol=yes resample=yes rfactor=2 minbinsz=0.1 ptsrc=yes psfcorr=yes emapbnds=no copyall=no chatter=2 clobber=yes debug=no gui=no mode="ql"
Caught St12out_of_range at the top level: vector::_M_range_check
Traceback (most recent call last):
  File "/home/szakirov/Desktop/SRMP/enrico/bin/enrico_sed", line 58, in <module>
    sed(config,infile)
  File "/home/szakirov/Desktop/SRMP/enrico/bin/enrico_sed", line 13, in sed
    run(infile)
  File "/home/szakirov/Desktop/SRMP/enrico/enrico/RunGTlike.py", line 113, in run
    FitRunner,Fit = GenAnalysisObjects(config)
  File "/home/szakirov/Desktop/SRMP/enrico/enrico/RunGTlike.py", line 89, in GenAnalysisObjects
    tag=typeirfs[evt], verbose = verbose)
  File "/home/szakirov/Desktop/SRMP/enrico/enrico/RunGTlike.py", line 23, in Analysis
    FitRunner.GenerateFits() #Generates fits files for the rest of the products
  File "/home/szakirov/Desktop/SRMP/enrico/enrico/fitmaker.py", line 79, in GenerateFits
    self.obs.SrcMap()
  File "/home/szakirov/Desktop/SRMP/enrico/enrico/gtfunction.py", line 391, in SrcMap
    srcMaps.run()
  File "/home/szakirov/Desktop/SRMP/ScienceTools-v11r5p3-fssc-20180124-x86_64-unknown-linux-gnu-libc2.17/x86_64-unknown-linux-gnu-libc2.17/lib/python/GtApp.py", line 72, in run
    raise RuntimeError, self.appName + " execution failed"
RuntimeError: gtsrcmaps execution failed

**Comment by davidsanchez** [comment]
Hi
the name of your source is empty 
<source name="" type="PointSource">
could it be this?
cheers
david

**Comment by hawkingsteven** [comment]
I think you're right, I am currently re-running the analysis. Thank you for your help. Hopefully it works!
