### ISSUE TITLE
gtlike execution fail

### ISSUE THREAD

**Issue by hawkingsteven** [gammapy/enrico#121]
Hello, I am running an analysis using ScienceTools-v10r0p5-fssc-20150518-x86_64-unknown-linux-gnu-libc2.12 
I'm using Scientific Linux 6.9
Everything was running smoothly with sed till this

# ************************************************************
# ***   9     gtlike --- Run likelihood analysis
# ************************************************************
Traceback (most recent call last):
  File "/home/Szakirov7/Desktop/SRMP/enrico/bin/enrico_sed", line 53, in <module>
    sed(config,infile)
  File "/home/Szakirov7/Desktop/SRMP/enrico/bin/enrico_sed", line 13, in sed
    run(infile)
  File "/home/Szakirov7/Desktop/SRMP/enrico/enrico/RunGTlike.py", line 115, in run
    FitRunner.PerformFit(Fit)
  File "/home/Szakirov7/Desktop/SRMP/enrico/enrico/fitmaker.py", line 150, in PerformFit
    self.log_like = Fit.fit(0,covar=True, optimizer=self.config['fitting']['optimizer'])
  File "/home/Szakirov7/Desktop/SRMP/ScienceTools-v10r0p5-fssc-20150518-x86_64-unknown-linux-gnu-libc2.12/x86_64-unknown-linux-gnu-libc2.12/lib/python/SummedLikelihood.py", line 95, in fit
    optObject=optObject)
  File "/home/Szakirov7/Desktop/SRMP/ScienceTools-v10r0p5-fssc-20150518-x86_64-unknown-linux-gnu-libc2.12/x86_64-unknown-linux-gnu-libc2.12/lib/python/SummedLikelihood.py", line 184, in _errors
    myOpt.find_min(verbosity, tol, self.tolType)
  File "/home/Szakirov7/Desktop/SRMP/ScienceTools-v10r0p5-fssc-20150518-x86_64-unknown-linux-gnu-libc2.12/x86_64-unknown-linux-gnu-libc2.12/lib/python/pyLikelihood.py", line 2093, in find_min
    return lib_pyLikelihood.Optimizer_find_min(*args)
RuntimeError: vector::_M_range_check

Can you recommend a course of action?

**Comment by davidsanchez** [comment]
hi
did you ran gtlike in command line? 
cheers

**Comment by mireianievas** [comment]
Have you checked if your fits files are healthy, they contain events and so? If they look fine, I would try playing a bit with the fitting options (tolerance, spetrum, sources that you put in the XML file and if their parameters are fixed, etc).
