### ISSUE TITLE
Error while generating flux points, TS Map

### ISSUE THREAD

**Issue by basuparth** [gammapy/enrico#126]
I am presently working with the Enrico data analysis suite and although enrico_sed, enrico_xml, and enrico_lc are functioning as expected I run into an error for enrico_tsmap and also when I try to generate flux points with enrico_sed. I am using the latest version of fermi science tools installed with anaconda. 

ERROR REPORT
(' Emin = ', 200.0, ' Emax = ', 300000.0, ' Nbins = ', 7)
[Message]: Submitting # 0 at energy 7745
Traceback (most recent call last):
  File "/home/parth/Downloads/x/fermi_data_analysis/enrico/bin/enrico_sed", line 53, in <module>
    sed(config,infile)
  File "/home/parth/Downloads/x/fermi_data_analysis/enrico/bin/enrico_sed", line 13, in sed
    run(infile)
  File "/home/parth/Downloads/x/fermi_data_analysis/enrico/enrico/RunGTlike.py", line 189, in run
    energybin.RunEbin(folder,Nbin,Fit,FitRunner,sedresult)
  File "/home/parth/Downloads/x/fermi_data_analysis/enrico/enrico/energybin.py", line 155, in RunEbin
    configfiles = PrepareEbin(Fit, FitRunner,sedresult)
  File "/home/parth/Downloads/x/fermi_data_analysis/enrico/enrico/energybin.py", line 130, in PrepareEbin
    NewFitObject = ChangeModel(comp, ener[ibin], ener[ibin + 1], srcname, Pref[ibin] ,Gamma[ibin])
  File "/home/parth/Downloads/x/fermi_data_analysis/enrico/enrico/energybin.py", line 29, in ChangeModel
    spectrum.getParam('Index').setFree(0)
  File "/home/parth/anaconda2/envs/fermi/lib/python2.7/site-packages/fermitools/pyLikelihood.py", line 3010, in setFree
    return _pyLikelihood.Parameter_setFree(self, free)
TypeError: in method 'Parameter_setFree', argument 2 of type 'bool' 

The error is the same for both flux points generation and tsmap.  It would be very kind of you if you could suggest a remedy. Thanks in advance.
[myanalysis.txt](https://github.com/gammapy/enrico/files/2875818/myanalysis.txt)

**Comment by mireianievas** [comment]
I think the issue is that up to now Parameter_setFree accepted a 0 as boolean (False). In the new versions of the Fermi Science Tools distributed through conda it actually expects the boolean. I have corrected it in a pull request.
