### ISSUE TITLE
enrico_applc error 

### ISSUE THREAD

**Issue by basuparth** [gammapy/enrico#132]
While executing enrico_applc command the following error is generated. The fermitools version is the anaconda version.  

# ************************************************************
# *** gtexposure --- compute the exposure
# ************************************************************
Traceback (most recent call last):
  File "/home/parth/SINP/enrico/bin/enrico_applc", line 50, in <module>
    run(infile)
  File "/home/parth/SINP/enrico/bin/enrico_applc", line 17, in run
    AppLC(infile)
  File "/home/parth/SINP/enrico/enrico/appertureLC.py", line 61, in AppLC
    Obs.GtExposure()
  File "/home/parth/SINP/enrico/enrico/gtfunction.py", line 136, in GtExposure
    exposure['evtype']= self.Configuration['event']['evtype']
  File "/home/parth/anaconda2/envs/fermi/lib/python2.7/site-packages/fermitools/GtApp.py", line 43, in __setitem__
    self.pars[key] = value
  File "/home/parth/anaconda2/envs/fermi/lib/python2.7/site-packages/fermitools/pil.py", line 73, in __setitem__
    raise KeyError, name
KeyError: 'evtype'

**Comment by davidsanchez** [comment]
Hi
I made a patch to correct this. could you try it
cheers
david

**Comment by basuparth** [comment]
Thanks @davidsanchez . Yes, it works fine now. I cross checked the results obtained from enrico with those from the official fermi tutorial and found them to be identical for the same data set and binning.
