### ISSUE TITLE
Enrico_sed  creates error for cluster submission.

### ISSUE THREAD

**Issue by 9635065235** [gammapy/enrico#143]
Hi,

I am using enrico_sed over a configuration file. If I run the analysis on my home computer everything works fine.

The moment I try to submit the job in cluster using enrico_sed I get the following error  in the log file:
 ~~~~~~~~ SETUP ENVIRONMENT ~~~~~~~~
HEADASNOQUERY: 1
PYTHONPATH: /lustre/fs22/group/hess/software/ScienceTools-v11r5p3-fssc-20180124-x86_64-unknown-linux-gnu-libc2.17/x86_64-unknown-linux-gnu-libc2.17/lib/python:
PATH: /usr/gridengine/scripts:/usr/gridengine/bin/lx-amd64:/batch/42768217.1.std.q:/usr/local/bin:/bin:/usr/bin:/afs/ifh.de/user/m/majumdar/bin:/afs/ifh.de/user/m/majumdar/scripts
Adding Enrico to PATH and PYTHONPATH
Setting environment variables for data file locations
Run enrico_setupcheck to check if you are set up correctly.
Check your PATH and PYTHONPATH if enrico_setup is not found or gives an error.
Traceback (most recent call last):
  File "/lustre/fs22/group/hess/software/enrico/enrico/RunGTlike.py", line 5, in <module>
    from enrico.fitmaker import FitMaker
  File "/lustre/fs22/group/hess/software/enrico/enrico/fitmaker.py", line 14, in <module>
    import astropy.io.fits as fits
ImportError: No module named astropy.io.fits``

It seems like the executed pythonpath has no module named 'astropy.io.fits'.
But I checked the pythonpath separately which has the module named 'astropy.io.fits'.

If you want more details to this problem please let me know.

Thanks in advance.

**Comment by davidsanchez** [comment]
Hi
thanks for using enrico. The only clusters supported yet are the CCIN2P3 at lyon (France), LAPP (france) and MPIK (Germany)
you can add yours by changing the script in the submission folder
best
david

**Comment by 9635065235** [comment]
Hi David,

Thanks for replying.
I changed LAPP submission script with my institute's batch details.
Still the problem remains.

Best,
Jhilik

**Comment by davidsanchez** [comment]
Hi
This is certainly because the setup for your farm is not correct. astropy does not come with the Fermitools
cheers
david

**Comment by 9635065235** [comment]
Okay. Thanks. 
Actually I was not getting the problem at all. I will recheck the setup of my farm.
Cheers,
Jhilik

**Comment by mireianievas** [comment]
pyfits is deprecated and replaced by astropy. I'm not sure if the ScienceTools people still support pyfits for old system, if that is the case maybe we can add some if-else statement in the imports.
