### ISSUE TITLE
Problem with gtmodel

### ISSUE THREAD

**Issue by Rishank2610** [gammapy/enrico#151]
While running "enrico_lc"  command my_analysis folder produces src files of about 4GB for each bin. I am trying to do analysis on 20 bins, i.e; about 80Gb of space. Also while running analysis there is an error message which keeps on recurring. 

#####

[LightCurve]: Reading files produced by enrico
[LightCurve] Warning: Fail reading config file : /home/rishank/flare1/LightCurve_20bins/Config_1_536544005.0_536630405.0
Job Number :  1
[LightCurve] Warning: Please have a look at this job log file
[LightCurve] Warning: Fail reading config file : /home/rishank/flare1/LightCurve_20bins/Config_2_536630405.0_536716805.0
Job Number :  2
[LightCurve] Warning: Please have a look at this job log file
[LightCurve] Warning: Fail reading config file : /home/rishank/flare1/LightCurve_20bins/Config_3_536716805.0_536803205.0
Job Number :  3
[LightCurve] Warning: Please have a look at this job log file
[LightCurve] Warning: Fail reading config file : /home/rishank/flare1/LightCurve_20bins/Config_4_536803205.0_536889605.0
Job Number :  4
[LightCurve] Warning: Please have a look at this job log file
[LightCurve] Warning: Fail reading config file : /home/rishank/flare1/LightCurve_20bins/Config_5_536889605.0_536976005.0
Job Number :  5
[LightCurve] Warning: Please have a look at this job log file
[LightCurve] Warning: Fail reading config file : /home/rishank/flare1/LightCurve_20bins/Config_6_536976005.0_537062405.0
Job Number :  6
[LightCurve] Warning: Please have a look at this job log file
[LightCurve] Warning: Fail reading config file : /home/rishank/flare1/LightCurve_20bins/Config_7_537062405.0_537148805.0
Job Number :  7
[LightCurve] Warning: Please have a look at this job log file
[LightCurve] Warning: Fail reading config file : /home/rishank/flare1/LightCurve_20bins/Config_8_537148805.0_537235205.0
Job Number :  8
[LightCurve] Warning: Please have a look at this job log file
[LightCurve] Warning: Fail reading config file : /home/rishank/flare1/LightCurve_20bins/Config_9_537235205.0_537321605.0
Job Number :  9
[LightCurve] Warning: Please have a look at this job log file
[LightCurve] Warning: Fail reading config file : /home/rishank/flare1/LightCurve_20bins/Config_10_537321605.0_537408005.0
Job Number :  10
[LightCurve] Warning: Please have a look at this job log file
[LightCurve] Warning: Fail reading config file : /home/rishank/flare1/LightCurve_20bins/Config_11_537408005.0_537494405.0
Job Number :  11
[LightCurve] Warning: Please have a look at this job log file
[LightCurve] Warning: Fail reading config file : /home/rishank/flare1/LightCurve_20bins/Config_12_537494405.0_537580805.0
Job Number :  12
[LightCurve] Warning: Please have a look at this job log file
[LightCurve] Warning: Fail reading config file : /home/rishank/flare1/LightCurve_20bins/Config_13_537580805.0_537667205.0
Job Number :  13
[LightCurve] Warning: Please have a look at this job log file
[LightCurve] Warning: Fail reading config file : /home/rishank/flare1/LightCurve_20bins/Config_14_537667205.0_537753605.0
Job Number :  14
[LightCurve] Warning: Please have a look at this job log file
[LightCurve] Warning: Fail reading config file : /home/rishank/flare1/LightCurve_20bins/Config_15_537753605.0_537840005.0
Job Number :  15
[LightCurve] Warning: Please have a look at this job log file
[LightCurve] Warning: Fail reading config file : /home/rishank/flare1/LightCurve_20bins/Config_16_537840005.0_537926405.0
Job Number :  16
[LightCurve] Warning: Please have a look at this job log file
[LightCurve] Warning: Fail reading config file : /home/rishank/flare1/LightCurve_20bins/Config_17_537926405.0_538012805.0
Job Number :  17
[LightCurve] Warning: Please have a look at this job log file
[LightCurve] Warning: Fail reading config file : /home/rishank/flare1/LightCurve_20bins/Config_18_538012805.0_538099205.0
Job Number :  18
[LightCurve] Warning: Please have a look at this job log file
[LightCurve] Warning: Fail reading config file : /home/rishank/flare1/LightCurve_20bins/Config_19_538099205.0_538185605.0
Job Number :  19
[LightCurve] Warning: Please have a look at this job log file
No Npred Plot produced
/home/rishank/anaconda2/envs/fermi/lib/python2.7/site-packages/matplotlib/axes/_base.py:2961: UserWarning: Attempting to set identical left==right results
in singular transformations; automatically expanding.
left=536500805.0, right=536500805.0
  'left=%s, right=%s') % (left, right))
Traceback (most recent call last):
  File "/home/rishank/enrico/bin/enrico_plot_lc", line 30, in <module>
    lcobject.PlotLC()
  File "/home/rishank/enrico/enrico/lightcurve.py", line 223, in PlotLC
    self._PlotLC()
  File "/home/rishank/enrico/enrico/lightcurve.py", line 384, in _PlotLC
    plt.tight_layout()
  File "/home/rishank/anaconda2/envs/fermi/lib/python2.7/site-packages/matplotlib/pyplot.py", line 1344, in tight_layout
    fig.tight_layout(pad=pad, h_pad=h_pad, w_pad=w_pad, rect=rect)
  File "/home/rishank/anaconda2/envs/fermi/lib/python2.7/site-packages/matplotlib/figure.py", line 2030, in tight_layout
    pad=pad, h_pad=h_pad, w_pad=w_pad, rect=rect)
  File "/home/rishank/anaconda2/envs/fermi/lib/python2.7/site-packages/matplotlib/tight_layout.py", line 351, in get_tight_layout_figure
    pad=pad, h_pad=h_pad, w_pad=w_pad)
  File "/home/rishank/anaconda2/envs/fermi/lib/python2.7/site-packages/matplotlib/tight_layout.py", line 130, in auto_adjust_subplotpars
    if ax.get_visible()])
  File "/home/rishank/anaconda2/envs/fermi/lib/python2.7/site-packages/matplotlib/axes/_base.py", line 4015, in get_tightbbox
    bb_xaxis = self.xaxis.get_tightbbox(renderer)
  File "/home/rishank/anaconda2/envs/fermi/lib/python2.7/site-packages/matplotlib/axis.py", line 1092, in get_tightbbox
    renderer)
  File "/home/rishank/anaconda2/envs/fermi/lib/python2.7/site-packages/matplotlib/axis.py", line 1075, in _get_tick_bboxes
    extent = tick.label1.get_window_extent(renderer)
  File "/home/rishank/anaconda2/envs/fermi/lib/python2.7/site-packages/matplotlib/text.py", line 933, in get_window_extent
    bbox, info, descent = self._get_layout(self._renderer)
  File "/home/rishank/anaconda2/envs/fermi/lib/python2.7/site-packages/matplotlib/text.py", line 308, in _get_layout
    ismath=False)
  File "/home/rishank/anaconda2/envs/fermi/lib/python2.7/site-packages/matplotlib/backends/backend_agg.py", line 226, in get_text_width_height_descent
    s, fontsize, renderer=self)
  File "/home/rishank/anaconda2/envs/fermi/lib/python2.7/site-packages/matplotlib/texmanager.py", line 602, in get_text_width_height_descent
    dvifile = self.make_dvi(tex, fontsize)
  File "/home/rishank/anaconda2/envs/fermi/lib/python2.7/site-packages/matplotlib/texmanager.py", line 393, in make_dvi
    stderr=subprocess.STDOUT)
  File "/home/rishank/anaconda2/envs/fermi/lib/python2.7/site-packages/subprocess32.py", line 337, in check_output
    process = Popen(stdout=PIPE, *popenargs, **kwargs)
  File "/home/rishank/anaconda2/envs/fermi/lib/python2.7/site-packages/subprocess32.py", line 617, in __init__
    restore_signals, start_new_session)
  File "/home/rishank/anaconda2/envs/fermi/lib/python2.7/site-packages/subprocess32.py", line 1415, in _execute_child
    raise child_exception_type(errno_num, err_msg)
OSError: [Errno 2] No such file or directory: 'latex'

#####

I am also attaching the whole log file to get the better idea
[lc_log.txt](https://github.com/gammapy/enrico/files/4980848/lc_log.txt)

**Comment by davidsanchez** [comment]
Apparently, you don't have enough space
cheers
david

**Comment by davidsanchez** [comment]
Enrico_lc produce an analysis for each time bin. 
the error message is due to the fact that enrico did not produced the config file  which is done before the production of the fits files. did you change someting in between?

**Comment by Rishank2610** [comment]
I did not change anything.
I followed the same steps as mentioned in the tutorial.
I did get some warning message in gtmodel while running enrico_sed before enrico_lc.

###
Parameter ptsrc not found in parameter group gtmodel (at /local/data/glitz1/gssctest/miniconda2/envs/build/conda-bld/fermitools_1580999712705/work/hoops/build/redhat6-x86_64-64bit-gcc48/src/hoops_group.cxx: 67)
Using default value of 1 for parameter ptsrc
Parameter minbinsz not found in parameter group gtmodel (at /local/data/glitz1/gssctest/miniconda2/envs/build/conda-bld/fermitools_1580999712705/work/hoops/build/redhat6-x86_64-64bit-gcc48/src/hoops_group.cxx: 67)
Using default value of 0.1 for parameter minbinsz
Parameter wmap not found in parameter group gtmodel (at /local/data/glitz1/gssctest/miniconda2/envs/build/conda-bld/fermitools_1580999712705/work/hoops/build/redhat6-x86_64-64bit-gcc48/src/hoops_group.cxx: 67)
Using default value of none for parameter wmap
real 64.29
user 55.72
sys 0.84
Not able to plot an upper limit in a SED diagram. UL computed?
###

I am also attaching the terminal log for the steps I followed.
[SED_log.txt](https://github.com/gammapy/enrico/files/4983050/SED_log.txt)

**Comment by davidsanchez** [comment]
Could you give me the output of an ls in  /home/rishank/flare1/LightCurve_20bins

**Comment by Rishank2610** [comment]
0_536457605.0_536544005.0_FRONTBACK.xml
1_536544005.0_536630405.0_FRONTBACK.xml
1ES1218+304_flare_1_LC_0_EvtCoarse.fits
1ES1218+304_flare_1_LC_0_FRONTBACK_BinnedMap.fits
1ES1218+304_flare_1_LC_0_FRONTBACK_CCUBE.fits
1ES1218+304_flare_1_LC_0_FRONTBACK_CountMap.fits
1ES1218+304_flare_1_LC_0_FRONTBACK_Evt.fits
1ES1218+304_flare_1_LC_0_FRONTBACK_ltCube.fits
1ES1218+304_flare_1_LC_0_FRONTBACK_MkTime.fits
1ES1218+304_flare_1_LC_0_FRONTBACK_PowerLaw_ModelMap.fits
1ES1218+304_flare_1_LC_0_FRONTBACK_PowerLaw_psf.fits
1ES1218+304_flare_1_LC_0_FRONTBACK_PowerLaw_ResidualMap.fits
1ES1218+304_flare_1_LC_0_FRONTBACK_PowerLaw_srcMap.fits
1ES1218+304_flare_1_LC_0_FRONTBACK_PowerLaw_SubtractMap.fits
1ES1218+304_flare_1_LC_1_EvtCoarse.fits
1ES1218+304_flare_1_LC_1_FRONTBACK_BinnedMap.fits
1ES1218+304_flare_1_LC_1_FRONTBACK_CCUBE.fits
1ES1218+304_flare_1_LC_1_FRONTBACK_CountMap.fits
1ES1218+304_flare_1_LC_1_FRONTBACK_Evt.fits
1ES1218+304_flare_1_LC_1_FRONTBACK_ltCube.fits
1ES1218+304_flare_1_LC_1_FRONTBACK_MkTime.fits
1ES1218+304_flare_1_LC_1_FRONTBACK_PowerLaw_ModelMap.fits
1ES1218+304_flare_1_LC_1_FRONTBACK_PowerLaw_psf.fits
1ES1218+304_flare_1_LC_1_FRONTBACK_PowerLaw_ResidualMap.fits
1ES1218+304_flare_1_LC_1_FRONTBACK_PowerLaw_srcMap.fits
1ES1218+304_flare_1_LC_1_FRONTBACK_PowerLaw_SubtractMap.fits
1ES1218+304_flare_1_LC_2_EvtCoarse.fits
1ES1218+304_flare_1_LC_2_FRONTBACK_BinnedMap.fits
1ES1218+304_flare_1_LC_2_FRONTBACK_CCUBE.fits
1ES1218+304_flare_1_LC_2_FRONTBACK_CountMap.fits
1ES1218+304_flare_1_LC_2_FRONTBACK_Evt.fits
1ES1218+304_flare_1_LC_2_FRONTBACK_ltCube.fits
1ES1218+304_flare_1_LC_2_FRONTBACK_MkTime.fits
1ES1218+304_flare_1_LC_2_FRONTBACK_PowerLaw_ModelMap.fits
1ES1218+304_flare_1_LC_2_FRONTBACK_PowerLaw_psf.fits
1ES1218+304_flare_1_LC_2_FRONTBACK_PowerLaw_ResidualMap.fits
1ES1218+304_flare_1_LC_2_FRONTBACK_PowerLaw_srcMap.fits
1ES1218+304_flare_1_LC_2_FRONTBACK_PowerLaw_SubtractMap.fits
1ES1218+304_flare_1_LC_3_EvtCoarse.fits
1ES1218+304_flare_1_LC_3_FRONTBACK_BinnedMap.fits
1ES1218+304_flare_1_LC_3_FRONTBACK_CCUBE.fits
1ES1218+304_flare_1_LC_3_FRONTBACK_CountMap.fits
1ES1218+304_flare_1_LC_3_FRONTBACK_Evt.fits
1ES1218+304_flare_1_LC_3_FRONTBACK_ltCube.fits
1ES1218+304_flare_1_LC_3_FRONTBACK_MkTime.fits
1ES1218+304_flare_1_LC_3_FRONTBACK_PowerLaw_ModelMap.fits
1ES1218+304_flare_1_LC_3_FRONTBACK_PowerLaw_psf.fits
1ES1218+304_flare_1_LC_3_FRONTBACK_PowerLaw_ResidualMap.fits
1ES1218+304_flare_1_LC_3_FRONTBACK_PowerLaw_srcMap.fits
1ES1218+304_flare_1_LC_3_FRONTBACK_PowerLaw_SubtractMap.fits
1ES1218+304_flare_1_LC_4_EvtCoarse.fits
1ES1218+304_flare_1_LC_4_FRONTBACK_BinnedMap.fits
1ES1218+304_flare_1_LC_4_FRONTBACK_CCUBE.fits
1ES1218+304_flare_1_LC_4_FRONTBACK_CountMap.fits
1ES1218+304_flare_1_LC_4_FRONTBACK_Evt.fits
1ES1218+304_flare_1_LC_4_FRONTBACK_ltCube.fits
1ES1218+304_flare_1_LC_4_FRONTBACK_MkTime.fits
1ES1218+304_flare_1_LC_4_FRONTBACK_PowerLaw_psf.fits
1ES1218+304_flare_1_LC_4_FRONTBACK_PowerLaw_srcMap.fits
1ES1218+304_PowerLaw_536457605_536544005_100_300000_flare_1_LC_0.results
1ES1218+304_PowerLaw_536544005_536630405_100_300000_flare_1_LC_1.results
1ES1218+304_PowerLaw_536630405_536716805_100_300000_flare_1_LC_2.results
1ES1218+304_PowerLaw_536716805_536803205_100_300000_flare_1_LC_3.results
1ES1218+304_PowerLaw_flare_1_LC_0_out.xml
1ES1218+304_PowerLaw_flare_1_LC_1_out.xml
1ES1218+304_PowerLaw_flare_1_LC_2_out.xml
1ES1218+304_PowerLaw_flare_1_LC_3_out.xml
1ES1218+304_PowerLaw_generation.log
2_536630405.0_536716805.0_FRONTBACK.xml
3_536716805.0_536803205.0_FRONTBACK.xml
4_536803205.0_536889605.0_FRONTBACK.xml
Config_0_536457605.0_536544005.0
Config_10_537321605.0_537408005.0
Config_11_537408005.0_537494405.0
Config_12_537494405.0_537580805.0
Config_13_537580805.0_537667205.0
Config_14_537667205.0_537753605.0
Config_1_536544005.0_536630405.0
Config_15_537753605.0_537840005.0
Config_16_537840005.0_537926405.0
Config_17_537926405.0_538012805.0
Config_18_538012805.0_538099205.0
Config_19_538099205.0_538185605.0
Config_2_536630405.0_536716805.0
Config_3_536716805.0_536803205.0
Config_4_536803205.0_536889605.0
Config_5_536889605.0_536976005.0
Config_6_536976005.0_537062405.0
Config_7_537062405.0_537148805.0
Config_8_537148805.0_537235205.0
Config_9_537235205.0_537321605.0
Roi_model.reg
