### ISSUE TITLE
Error while running enrico_sed

### ISSUE THREAD

**Issue by Rishank2610** [gammapy/enrico#152]
I am using Enrico for analysis of Fermi-Lat data. I did not get any error while installing Enrico and Fermitools. While running enrico_sed command I am getting the following error.
""
# ************************************************************
# ***  15    gtmodel --- Make model map
# ************************************************************
time -p gtmodel srcmaps=/home/rishank/58119-58299/1ES1218+304_flare_1_FRONTBACK_PowerLaw_srcMap.fits srcmdl=/home/rishank/58119-58299/1ES1218+304_PowerLaw_flare_1_out.xml outfile=/home/rishank/58119-58299/1ES1218+304_flare_1_FRONTBACK_PowerLaw_ModelMap.fits irfs="P8R3_SOURCE_V2" evtype="INDEF" expcube=/home/rishank/58119-58299/1ES1218+304_flare_1_FRONTBACK_ltCube.fits bexpmap=/home/rishank/58119-58299/1ES1218+304_flare_1_FRONTBACK_BinnedMap.fits convol=yes resample=yes rfactor=2 outtype="CMAP" psfcorr=yes phased_expmap=none edisp_bins=0 chatter=2 clobber=yes debug=no gui=no mode="ql"

WARNING: version mismatch between CFITSIO header (v3.43) and linked library (v3.41).

Parameter ptsrc not found in parameter group gtmodel (at /local/data/glitz1/gssctest/miniconda2/envs/build/conda-bld/fermitools_1580999712705/work/hoops/build/redhat6-x86_64-64bit-gcc48/src/hoops_group.cxx: 67)
Using default value of 1 for parameter ptsrc
Parameter minbinsz not found in parameter group gtmodel (at /local/data/glitz1/gssctest/miniconda2/envs/build/conda-bld/fermitools_1580999712705/work/hoops/build/redhat6-x86_64-64bit-gcc48/src/hoops_group.cxx: 67)
Using default value of 0.1 for parameter minbinsz
Parameter wmap not found in parameter group gtmodel (at /local/data/glitz1/gssctest/miniconda2/envs/build/conda-bld/fermitools_1580999712705/work/hoops/build/redhat6-x86_64-64bit-gcc48/src/hoops_group.cxx: 67)
Using default value of none for parameter wmap
real 27.64
user 27.38
sys 0.62
Traceback (most recent call last):
  File "/home/rishank/enrico/bin/enrico_sed", line 55, in <module>
    sed(config,infile)
  File "/home/rishank/enrico/bin/enrico_sed", line 13, in sed
    run(infile)
  File "/home/rishank/enrico/enrico/RunGTlike.py", line 256, in run
    plot_sed_fromconfig(infile,ignore_missing_bins=True)
  File "/home/rishank/enrico/enrico/plotting.py", line 611, in plot_sed_fromconfig
    PlotSED(config,Param,ignore_missing_bins)
  File "/home/rishank/enrico/enrico/plotting.py", line 565, in PlotSED
    plt.tight_layout()
  File "/home/rishank/anaconda2/envs/fermi/lib/python2.7/site-packages/matplotlib/pyplot.py", line 1344, in tight_layout
    fig.tight_layout(pad=pad, h_pad=h_pad, w_pad=w_pad, rect=rect)
  File "/home/rishank/anaconda2/envs/fermi/lib/python2.7/site-packages/matplotlib/figure.py", line 2030, in tight_layout
    pad=pad, h_pad=h_pad, w_pad=w_pad, rect=rect)
  File "/home/rishank/anaconda2/envs/fermi/lib/python2.7/site-packages/matplotlib/tight_layout.py", line 351, in get_tight_layout_figure
    pad=pad, h_pad=h_pad, w_pad=w_pad)
  File "/home/rishank/anaconda2/envs/fermi/lib/python2.7/site-packages/matplotlib/tight_layout.py", line 130, in auto_adjust_subplotpars
    if ax.get_visible()])
  File "/home/rishank/anaconda2/envs/fermi/lib/python2.7/site-packages/matplotlib/axes/_base.py", line 4009, in get_tightbbox
    bb.append(self.title.get_window_extent(renderer))
  File "/home/rishank/anaconda2/envs/fermi/lib/python2.7/site-packages/matplotlib/text.py", line 933, in get_window_extent
    bbox, info, descent = self._get_layout(self._renderer)
  File "/home/rishank/anaconda2/envs/fermi/lib/python2.7/site-packages/matplotlib/text.py", line 308, in _get_layout
    ismath=False)
  File "/home/rishank/anaconda2/envs/fermi/lib/python2.7/site-packages/matplotlib/backends/backend_agg.py", line 226, in get_text_width_height_descent
    s, fontsize, renderer=self)
  File "/home/rishank/anaconda2/envs/fermi/lib/python2.7/site-packages/matplotlib/texmanager.py", line 602, in get_text_width_height_descent
    dvifile = self.make_dvi(tex, fontsize)
  File "/home/rishank/anaconda2/envs/fermi/lib/python2.7/site-packages/matplotlib/texmanager.py", line 393, in make_dvi
    stderr=subprocess.STDOUT)
  File "/home/rishank/anaconda2/envs/fermi/lib/python2.7/site-packages/subprocess32.py", line 337, in check_output
    process = Popen(stdout=PIPE, *popenargs, **kwargs)
  File "/home/rishank/anaconda2/envs/fermi/lib/python2.7/site-packages/subprocess32.py", line 617, in __init__
    restore_signals, start_new_session)
  File "/home/rishank/anaconda2/envs/fermi/lib/python2.7/site-packages/subprocess32.py", line 1415, in _execute_child
    raise child_exception_type(errno_num, err_msg)
OSError: [Errno 2] No such file or directory: 'latex'
""
I have also got this error while running enrico_lc command separately. 
I am also attaching a log of the commands I followed for analysis.
[sed_log.txt](https://github.com/gammapy/enrico/files/4993129/sed_log.txt)

**Comment by davidsanchez** [comment]
I try to solve that

**Comment by davidsanchez** [comment]
Could you give me the config file. I cant reproduce the error

**Comment by Rishank2610** [comment]
Yes. I am sharing the .txt file of config
[myanalysis.txt](https://github.com/gammapy/enrico/files/4994586/myanalysis.txt)

**Comment by davidsanchez** [comment]
Could you try the new version please

**Comment by Rishank2610** [comment]
I tried the new version. This time I am getting a different error.
"
Parameter ptsrc not found in parameter group gtmodel (at /local/data/glitz1/gssctest/miniconda2/envs/build/conda-bld/fermitools_1580999712705/work/hoops/build/redhat6-x86_64-64bit-gcc48/src/hoops_group.cxx: 67)
Using default value of 1 for parameter ptsrc
Parameter minbinsz not found in parameter group gtmodel (at /local/data/glitz1/gssctest/miniconda2/envs/build/conda-bld/fermitools_1580999712705/work/hoops/build/redhat6-x86_64-64bit-gcc48/src/hoops_group.cxx: 67)
Using default value of 0.1 for parameter minbinsz
Parameter wmap not found in parameter group gtmodel (at /local/data/glitz1/gssctest/miniconda2/envs/build/conda-bld/fermitools_1580999712705/work/hoops/build/redhat6-x86_64-64bit-gcc48/src/hoops_group.cxx: 67)
Using default value of none for parameter wmap
real 26.47
user 26.37
sys 0.38
Traceback (most recent call last):
  File "/home/rishank/enrico/bin/enrico_sed", line 55, in <module>
    sed(config,infile)
  File "/home/rishank/enrico/bin/enrico_sed", line 13, in sed
    run(infile)
  File "/home/rishank/enrico/enrico/RunGTlike.py", line 259, in run
    plot_sed_fromconfig(infile,ignore_missing_bins=True)
  File "/home/rishank/enrico/enrico/plotting.py", line 621, in plot_sed_fromconfig
    PlotSED(config,Param,ignore_missing_bins)
  File "/home/rishank/enrico/enrico/plotting.py", line 575, in PlotSED
    plt.tight_layout()
  File "/home/rishank/anaconda2/envs/fermi/lib/python2.7/site-packages/matplotlib/pyplot.py", line 1344, in tight_layout
    fig.tight_layout(pad=pad, h_pad=h_pad, w_pad=w_pad, rect=rect)
  File "/home/rishank/anaconda2/envs/fermi/lib/python2.7/site-packages/matplotlib/figure.py", line 2030, in tight_layout
    pad=pad, h_pad=h_pad, w_pad=w_pad, rect=rect)
  File "/home/rishank/anaconda2/envs/fermi/lib/python2.7/site-packages/matplotlib/tight_layout.py", line 351, in get_tight_layout_figure
    pad=pad, h_pad=h_pad, w_pad=w_pad)
  File "/home/rishank/anaconda2/envs/fermi/lib/python2.7/site-packages/matplotlib/tight_layout.py", line 130, in auto_adjust_subplotpars
    if ax.get_visible()])
  File "/home/rishank/anaconda2/envs/fermi/lib/python2.7/site-packages/matplotlib/axes/_base.py", line 4009, in get_tightbbox
    bb.append(self.title.get_window_extent(renderer))
  File "/home/rishank/anaconda2/envs/fermi/lib/python2.7/site-packages/matplotlib/text.py", line 933, in get_window_extent
    bbox, info, descent = self._get_layout(self._renderer)
  File "/home/rishank/anaconda2/envs/fermi/lib/python2.7/site-packages/matplotlib/text.py", line 308, in _get_layout
    ismath=False)
  File "/home/rishank/anaconda2/envs/fermi/lib/python2.7/site-packages/matplotlib/backends/backend_agg.py", line 226, in get_text_width_height_descent
    s, fontsize, renderer=self)
  File "/home/rishank/anaconda2/envs/fermi/lib/python2.7/site-packages/matplotlib/texmanager.py", line 602, in get_text_width_height_descent
    dvifile = self.make_dvi(tex, fontsize)
  File "/home/rishank/anaconda2/envs/fermi/lib/python2.7/site-packages/matplotlib/texmanager.py", line 393, in make_dvi
    stderr=subprocess.STDOUT)
  File "/home/rishank/anaconda2/envs/fermi/lib/python2.7/site-packages/subprocess32.py", line 337, in check_output
    process = Popen(stdout=PIPE, *popenargs, **kwargs)
  File "/home/rishank/anaconda2/envs/fermi/lib/python2.7/site-packages/subprocess32.py", line 617, in __init__
    restore_signals, start_new_session)
  File "/home/rishank/anaconda2/envs/fermi/lib/python2.7/site-packages/subprocess32.py", line 1415, in _execute_child
    raise child_exception_type(errno_num, err_msg)
OSError: [Errno 2] No such file or directory: 'latex'
"

All the steps worked until the fitmaker(Results of fit).
I am attaching the config file and the log file.
[log.txt](https://github.com/gammapy/enrico/files/5045965/log.txt)
[myanalysis.txt](https://github.com/gammapy/enrico/files/5045969/myanalysis.txt)
