### ISSUE TITLE
enrico_sed- ImportError: libCLHEP-2.4.4.0.so: cannot open shared object file

### ISSUE THREAD

**Issue by Marcas98** [gammapy/enrico#160]
Hi,

I have problem running enrico_sed, I have tried to download the CLHEP library but it still does not work.

(fermi) mitsa@blazar:~/myanalysis$ enrico_sed myanalysis.conf
Traceback (most recent call last):
  File "/home/mitsa/enrico/bin/enrico_sed", line 9, in <module>
    from enrico.RunGTlike import run
  File "/home/mitsa/enrico/enrico/RunGTlike.py", line 5, in <module>
    from enrico.fitmaker import FitMaker
  File "/home/mitsa/enrico/enrico/fitmaker.py", line 18, in <module>
    from UnbinnedAnalysis import UnbinnedAnalysis, UnbinnedObs
  File "/home/mitsa/anaconda3/envs/fermi/lib/python3.7/site-packages/fermitools/UnbinnedAnalysis.py", line 12, in <module>
    import pyLikelihood as pyLike
  File "/home/mitsa/anaconda3/envs/fermi/lib/python3.7/site-packages/fermitools/pyLikelihood.py", line 15, in <module>
    import _pyLikelihood
ImportError: libCLHEP-2.4.4.0.so: cannot open shared object file: No such file or directory

**Comment by davidsanchez** [comment]
Hi
looks more like a problem with the fermitools since this is at the level of rom UnbinnedAnalysis import UnbinnedAnalysis, UnbinnedObs

David
