### ISSUE TITLE
problem with flux points

### ISSUE THREAD

**Issue by astrolog1986** [gammapy/enrico#73]
Hi,

When I use enrico_sed .conf it works for all steps but as soon as it tries to calculate the flux points it stops and gives error. This is the error
```
# *** Preparing submission of fit into energy bins ***
# ************************************************************
('Emin = ', 100.0, ' Emax = ', 300000.0, ' Nbins = ', 5)
[Message]: Submition # 0 at energy 222
Traceback (most recent call last):
  File "/opt/enrico/bin/enrico_sed", line 58, in <module>
    sed(config,infile)
  File "/opt/enrico/bin/enrico_sed", line 13, in sed
    run(infile)
  File "/opt/enrico/enrico/RunGTlike.py", line 74, in run
    energybin.RunEbin(folder,Nbin,Fit,FitRunner)
  File "/opt/enrico/enrico/energybin.py", line 116, in RunEbin
    configfiles = PrepareEbin(Fit, FitRunner)
  File "/opt/enrico/enrico/energybin.py", line 97, in PrepareEbin
    NewFitObject = ChangeModel(Fit, ener[ibin], ener[ibin + 1], srcname, Pref[ibin] ,Gamma[ibin])
  File "/opt/enrico/enrico/energybin.py", line 31, in ChangeModel
    Fit.logLike.getSource(name).getSrcFuncs()['Spectrum'].getParam('Index').setBounds(Gamma_min,Gamma_max)
  File "/opt/Fermi/x86_64-unknown-linux-gnu-libc2.5/lib/python/pyLikelihood.py", line 1595, in setBounds
    return lib_pyLikelihood.Parameter_setBounds(*args)
RuntimeError: Attempt to set bounds that exclude the existing value.
```
Can you please help me to solve this problem.
Thank you in advance.
Best regards

**Comment by davidsanchez** [comment]
the code try to change a parameter to create the new xml file. change the boundary of the parameters in the xml file and this should work. btw, this is not a  good sign and you should check the results also
cheers

**Comment by astrolog1986** [comment]
thanks! It seems the problem was that I used the model file which was not generated with enrico. Now it works.
