### ISSUE TITLE
Bins from data [AppLC] giving wrong bin definition

### ISSUE THREAD

**Issue by migueln** [gammapy/enrico#88]
Hi,

I'm having some troubles with this option. Apparently some beginning and ending bins are not well defined (just checking with numpy if some times in the second column are smaller than the ones of the first column it returns True for some of them)

[Timebin.txt](https://github.com/gammapy/enrico/files/207586/Timebin.txt)

**Comment by davidsanchez** [comment]
Hi

Could you give the me the config file you use ? I'll like to reproduce this bug
thanks

**Comment by mireianievas** [comment]
This for instance

http://pastebin.com/jkvJ4Qpk

Gives 

`This is gtbin version ScienceTools-v10r0p5-fssc-20150518
Caught St13runtime_error at the top level: OrderedBinner: interval number 28 has invalid range [4.85247e+08, 4.85242e+08)
Traceback (most recent call last):
  File "/home/fermiuser/enrico//bin/enrico_applc", line 50, in <module>
    run(infile)
  File "/home/fermiuser/enrico//bin/enrico_applc", line 17, in run
    AppLC(infile)
  File "/home/fermiuser/enrico/enrico/appertureLC.py", line 54, in AppLC
    Obs.GtLCbin(dt = 0)
  File "/home/fermiuser/enrico/enrico/gtfunction.py", line 136, in GtLCbin
    evtbin.run()
  File "/home/fermiuser/AstroSoft/ScienceTools/x86_64-unknown-linux-gnu-libc2.12/lib/python/GtApp.py", line 72, in run
    raise RuntimeError, self.appName + " execution failed"
RuntimeError: gtbin execution failed
`

**Comment by mireianievas** [comment]
Ok, it might be enough to sort the time array?

In appertureLC.py: 

```
def MakeTimebinFile(Obs,timefile):
    from numpy import sort
    spfile = pyfits.open(Obs.eventfile)
    Time = sort(spfile[1].data.field(9)[:-1])

```

It doesn't crash and gives an aperture LC. Not sure it that's safe and correct though.

**Comment by davidsanchez** [comment]
should be fine.
