### ISSUE TITLE
LC error - LAT exposure off periods 

### ISSUE THREAD

**Issue by mhashad** [gammapy/enrico#94]
Hi,
When I create LC of parameters showed in the attached config file, the enrico_LC command gives me an error at a certain bin and when I regenerate the same process using Photometry method it gives me the whole results and while I check the data I've found that at the certain bin ,that gives me the error by Likelihood method,the corresponding exposure for that bin is equal to zero that makes me enforced to divide the whole period to sub-periods to avoid the bins that have exposure = 0, so, do you have a method to carry out the enrico_LC for the whole period one time that contains bins with exposure=0 .

This is the error: 
Caught St13runtime_error at the top level: No GTIs found in input event file(s).
Traceback (most recent call last):
  File "/home/hep/soft-instillation/enrico//bin/enrico_lc", line 29, in <module>
    lc.MakeLC()
  File "/home/hep/soft-instillation/enrico/enrico/lightcurve.py", line 174, in MakeLC
    self._MakeLC()
  File "/home/hep/soft-instillation/enrico/enrico/lightcurve.py", line 134, in _MakeLC
    run(self.configfile[i])#run in command line
  File "/home/hep/soft-instillation/enrico/enrico/RunGTlike.py", line 55, in run
    FitRunner,Fit = GenAnalysisObjects(config)
  File "/home/hep/soft-instillation/enrico/enrico/RunGTlike.py", line 43, in GenAnalysisObjects
    FitRunner = Analysis(folder, config, tag="", verbose = verbose)
  File "/home/hep/soft-instillation/enrico/enrico/RunGTlike.py", line 18, in Analysis
    FitRunner.GenerateFits() #Generates fits files
  File "/home/hep/soft-instillation/enrico/enrico/fitmaker.py", line 54, in GenerateFits
    self.obs.DiffResps()#run gtdiffresp
  File "/home/hep/soft-instillation/enrico/enrico/gtfunction.py", line 269, in DiffResps
    diffResps.run()
  File "/home/hep/tools-fermi/ScienceTools-v10r0p5-fssc-20150518-x86_64-unknown-linux-gnu-libc2.19-0/x86_64-unknown-linux-gnu-libc2.19-0/lib/python/GtApp.py", line 72, in run
    raise RuntimeError, self.appName + " execution failed"
RuntimeError: gtdiffrsp execution failed

Thanks
[myanalysis.txt](https://github.com/gammapy/enrico/files/298829/myanalysis.txt)

**Comment by davidsanchez** [comment]
Hi

I guess you are make LC with short time bins (below the orbit) right?
there is workaround with enrico : 
enrico_lc produced configuration files (named Config*) and run the very same tool as enrico_sed after. you can go to the directory of the LC and run enrico_sed Config*


then run enrico_plot_lc will work. this is transparent for enrico
cheers
david
