### ISSUE TITLE
Problem with TSmap generation

### ISSUE THREAD

**Issue by pmunar** [gammapy/enrico#99]
Hi!

I am trying to produce a TSmap but I get some errors in each iteration. I ran first the command enrico_sed and then tried to produce the TSmap with the row method.

The error that it spits out is:

Generating SourceMap for Spurious.....................!
Traceback (most recent call last):
  File "/home/pmunar/bin/enrico/enrico/tsmap.py", line 216, in <module>
    TSmap.FitOneRow(float(sys.argv[2]),int(sys.argv[4]))
  File "/home/pmunar/bin/enrico/enrico/tsmap.py", line 109, in FitOneRow
    self.FitOnePixel(ra,dec,i,j)
  File "/home/pmunar/bin/enrico/enrico/tsmap.py", line 92, in FitOnePixel
    _,TSFit = GenAnalysisObjects(self.config,xmlfile=self.tsfolder+"/model_"+str(ra)+"_"+str(dec)+".xml") #get the Fit object
  File "/home/pmunar/bin/enrico/enrico/RunGTlike.py", line 46, in GenAnalysisObjects
    Fit = FitRunner.CreateLikeObject()
  File "/home/pmunar/bin/enrico/enrico/fitmaker.py", line 97, in CreateLikeObject
    if Fit.model.srcs[self.obs.srcname].spectrum().genericName()=="PowerLaw" or Fit.model.srcs[self.obs.srcname].spectrum().genericName()=="PowerLaw2":
KeyError: 'my_source'

The name of the source of interest in the xml model and in the config file is my_source and I am modeling it with a PowerLaw. 
I do not understand this error, since I produced some other TSmaps in the past and they worked well.

Thanks a lot!

Pere.

**Comment by davidsanchez** [comment]
Hi
could you attache the config and xml file please
thanks
david
